const TYPO_MAP: Record<string, string> = {
  teh: 'the',
  hte: 'the',
  adn: 'and',
  recieve: 'receive',
  recieved: 'received',
  recieveing: 'receiving',
  acheive: 'achieve',
  acheived: 'achieved',
  acheiving: 'achieving',
  beleive: 'believe',
  beleived: 'believed',
  beleiving: 'believing',
  wich: 'which',
  whic: 'which',
  seperate: 'separate',
  separetely: 'separately',
  definately: 'definitely',
  definatly: 'definitely',
  definetly: 'definitely',
  ocassion: 'occasion',
  occassion: 'occasion',
  occassionally: 'occasionally',
  occured: 'occurred',
  occuring: 'occurring',
  occurence: 'occurrence',
  occurences: 'occurrences',
  begining: 'beginning',
  beginings: 'beginnings',
  wierd: 'weird',
  intresting: 'interesting',
  intersting: 'interesting',
  langauge: 'language',
  languges: 'languages',
  lenght: 'length',
  wieght: 'weight',
  alot: 'a lot',
  ammount: 'amount',
  appart: 'apart',
  arguement: 'argument',
  availible: 'available',
  basicly: 'basically',
  becasue: 'because',
  becuase: 'because',
  becouse: 'because',
  becuse: 'because',
  buisness: 'business',
  bizness: 'business',
  carreer: 'career',
  cemetary: 'cemetery',
  charecter: 'character',
  choosen: 'chosen',
  committment: 'commitment',
  commited: 'committed',
  commiting: 'committing',
  comparision: 'comparison',
  consious: 'conscious',
  conciousness: 'consciousness',
  conected: 'connected',
  contious: 'continuous',
  councel: 'counsel',
  critisism: 'criticism',
  desicion: 'decision',
  developement: 'development',
  devolopment: 'development',
  dicotomy: 'dichotomy',
  differnt: 'different',
  differrent: 'different',
  disappearred: 'disappeared',
  dissapear: 'disappear',
  dissapeared: 'disappeared',
  dissappear: 'disappear',
  dissappointed: 'disappointed',
  divison: 'division',
  embarassed: 'embarrassed',
  embarassment: 'embarrassment',
  enviroment: 'environment',
  enviromental: 'environmental',
  equiptment: 'equipment',
  essentail: 'essential',
  exagerate: 'exaggerate',
  exagerated: 'exaggerated',
  exellent: 'excellent',
  exelent: 'excellent',
  existance: 'existence',
  experiance: 'experience',
  extremly: 'extremely',
  familarity: 'familiarity',
  feasable: 'feasible',
  finaly: 'finally',
  finially: 'finally',
  foriegn: 'foreign',
  freind: 'friend',
  freinds: 'friends',
  genuienly: 'genuinely',
  govenment: 'government',
  goverment: 'government',
  happend: 'happened',
  helpfull: 'helpful',
  hierachy: 'hierarchy',
  hindrence: 'hindrance',
  hypocracy: 'hypocrisy',
  immediatly: 'immediately',
  incase: 'in case',
  independant: 'independent',
  infalible: 'infallible',
  intellegent: 'intelligent',
  interupt: 'interrupt',
  interprete: 'interpret',
  irregardless: 'regardless',
  knowlege: 'knowledge',
  knowlegde: 'knowledge',
  labled: 'labeled',
  lieing: 'lying',
  maintenence: 'maintenance',
  managable: 'manageable',
  medecine: 'medicine',
  moveable: 'movable',
  neccessary: 'necessary',
  necesary: 'necessary',
  neccessarily: 'necessarily',
  noticable: 'noticeable',
  noticably: 'noticeably',
  oppertunity: 'opportunity',
  oportunity: 'opportunity',
  orignally: 'originally',
  peice: 'piece',
  persistant: 'persistent',
  prefered: 'preferred',
  pronounciation: 'pronunciation',
  prophacy: 'prophecy',
  phrophet: 'prophet',
  pupose: 'purpose',
  quater: 'quarter',
  quesion: 'question',
  realise: 'realize',
  realiseed: 'realized',
  recomend: 'recommend',
  recommand: 'recommend',
  recommendad: 'recommended',
  relevent: 'relevant',
  religous: 'religious',
  reseach: 'research',
  responcibility: 'responsibility',
  resposibility: 'responsibility',
  sence: 'sense',
  sofware: 'software',
  sucess: 'success',
  sucessful: 'successful',
  suprisingly: 'surprisingly',
  supprise: 'surprise',
  supercede: 'supersede',
  suposedly: 'supposedly',
  suposed: 'supposed',
  tendancy: 'tendency',
  thier: 'their',
  therfore: 'therefore',
  threfore: 'therefore',
  thru: 'through',
  tounge: 'tongue',
  truely: 'truly',
  twelth: 'twelfth',
  unforgetable: 'unforgettable',
  unfortunatly: 'unfortunately',
  usefull: 'useful',
  vengence: 'vengeance',
  versitile: 'versatile',
  visable: 'visible',
  vitory: 'victory',
  wether: 'whether',
  widsom: 'wisdom',
  yatch: 'yacht',
  yor: 'your',
  youself: 'yourself',
}

export function isLetter(ch: string): boolean {
  return /[A-Za-z]/.test(ch)
}

export function isWordBoundary(ch: string | undefined): boolean {
  return ch == null || !isLetter(ch)
}

function fixDoubleCap(word: string): string | null {
  if (word.length < 2) return null
  const first = word[0]
  const second = word[1]
  if (first === first.toUpperCase() && second === second.toUpperCase() && first !== first.toLowerCase()) {
    if (word.length > 2 && word.slice(2) === word.slice(2).toUpperCase()) return null
    return first + word.slice(1).toLowerCase()
  }
  return null
}

export function correctWord(word: string): string | null {
  if (word === 'i') return 'I'
  if (word.length === 1) return null
  const double = fixDoubleCap(word)
  if (double) return double
  const good = TYPO_MAP[word.toLowerCase()]
  if (!good) return null
  if (word === word.toUpperCase() && word.length > 1) return good.toUpperCase()
  return word[0] === word[0].toUpperCase() ? good[0].toUpperCase() + good.slice(1) : good
}

/** Longest trustworthy word to autocorrect in one typing burst. */
export const AUTOCORRECT_LIMIT = 200